const actors = ["Johnny Depp", "Al Pacino", "Robert De Niro", "Kevin Spacey", "Denzel Washington", "Russell Crowe", "Brad Pitt", "Angelina Jolie", "Leonardo DiCaprio", "Tom Cruise", "John Travolta", "Arnold Schwarzenegger", "Sylvester Stallone", "Kate Winslet", "Christian Bale", "Morgan Freeman", "Keanu Reeves", "Nicolas Cage", "Hugh Jackman", "Edward Norton", "Bruce Willis", "Tom Hanks", "Charlize Theron", "Will Smith", "Sean Connery", "Keira Knightley", "Vin Diesel", "Matt Damon", "Richard Gere", "Catherine Zeta - Jones", "Clive Owen", "Mel Gibson", "George Clooney", "Jack Nicholson", "Scarlett Johansson", "Tom Hardy", "Robert Downey Jr.", "Orlando Bloom", "Ian McKellen", "Antonio Banderas", "Guy Pearce", "Samuel L.Jackson", "Sandra Bullock", "Meg Ryan", "Megan Fox", "Nicole Kidman", "Gerard Butler", "Simon Baker", "Cameron Diaz", "Katherine Heigl"];
const artists = ["Rihanna", "Drake", "Coldplay", "Eminem", "Maroon", "Ed Sheeran", "Bruno Mars", "Kanye West", "The Weeknd", "Adele", "Beyoncé", "U2", "Justin Bieber", "Taylor Swift", "Kendrick Lamar", "Katy Perry", "Red Hot Chili Peppers", "Calvin Harris", "Nicki Minaj", "Lil Wayne", "Imagine Dragons", "Lady Gaga", "Chris Brown", "David Guetta", "Ariana Grande", "Lana Del Rey", "Queen", "Justin Timberlake", "The Killers", "Wiz Khalifa", "Usher", "Radiohead", "Arctic Monkeys", "Kings of Leon", "Post Malone", "Ellie Goulding", "Pitbull", "Green Day", "J.Cole", "Black Eyed Peas", "Muse", "Miley Cyrus", "Jason Derulo", "Mumford & Sons", "Sia", "The Rolling Stones", "Metallica", "Sam Smith", "A$AP Rocky", "Fleetwood Mac"];
const browsers = ["Firefox", "Google Chrome", "Microsoft Edge", "Apple Safari", "Opera", "Brave", "Vivaldi", "DuckDuckgo"];
const cities = ["Kabul", "Tirana (Tirane)", "Algiers", "Andorra la Vella", "Luanda", "Saint John's", "Buenos Aires", "Yerevan", "Canberra", "Vienna", "Baku", "Nassau", "Manama", "Dhaka", "Bridgetown", "Minsk", "Brussels", "Belmopan", "Porto Novo", "Thimphu", "La Paz", "Sarajevo", "Gaborone", "Brasilia", "Bandar Seri Begawan", "Sofia", "Ouagadougou", "Gitega", "Phnom Penh", "Yaounde", "Ottawa", "Praia", "Bangui", "N'Djamena", "Santiago", "Beijing", "Bogota", "Moroni", "Kinshasa", "Brazzaville", "San Jose", "Yamoussoukro", "Zagreb", "Havana", "Nicosia", "Prague", "Copenhagen", "Djibouti", "Roseau", "Santo Domingo", "Dili", "Quito", "Cairo", "San Salvador", "London", "Malabo", "Asmara", "Tallinn", "Mbabana", "Addis Ababa", "Palikir", "Suva", "Helsinki", "Paris", "Libreville", "Banjul", "Tbilisi", "Berlin", "Accra", "Athens", "Saint George's", "Guatemala City", "Conakry", "Bissau", "Georgetown", "Port au Prince", "Tegucigalpa", "Budapest", "Reykjavik", "New Delhi", "Jakarta", "Tehran", "Baghdad", "Dublin", "Jerusalem", "Rome", "Kingston", "Tokyo", "Amman", "Nur - Sultan", "Nairobi", "Tarawa Atoll", "Pristina", "Kuwait City", "Bishkek", "Vientiane", "Riga", "Beirut", "Maseru", "Monrovia", "Tripoli", "Vaduz", "Vilnius", "Luxembourg", "Antananarivo", "Lilongwe", "Kuala Lumpur", "Male", "Bamako", "Valletta", "Majuro", "Nouakchott", "Port Louis", "Mexico City", "Chisinau", "Monaco", "Ulaanbaatar", "Podgorica", "Rabat", "Maputo", "Nay Pyi Taw", "Windhoek", "Kathmandu", "Amsterdam", "Wellington", "Managua", "Niamey", "Abuja", "Pyongyang", "Skopje", "Belfast", "Oslo", "Muscat", "Islamabad", "Melekeok", "Panama City", "Port Moresby", "Asuncion", "Lima", "Manila", "Warsaw", "Lisbon", "Doha", "Bucharest", "Moscow", "Kigali", "Basseterre", "Castries", "Kingstown", "Apia", "San Marino", "Sao Tome", "Riyadh", "Edinburgh", "Dakar", "Belgrade", "Victoria", "Freetown", "Singapore", "Bratislava", "Ljubljana", "Honiara", "Mogadishu", "Cape Town", "Seoul", "Juba", "Madrid", "Sri Jayawardenapura Kotte", "Khartoum", "Paramaribo", "Stockholm", "Bern", "Damascus", "Taipei", "Dushanbe", "Dodoma", "Bangkok", "Lome", "Nuku'alofa", "Port of Spain", "Tunis", "Ankara", "Ashgabat", "Funafuti", "Kampala", "Kiev", "Abu Dhabi", "London", "Washington D.C.", "Montevideo", "Tashkent", "Port Vila", "Vatican City", "Caracas", "Hanoi", "Cardiff", "Sana'a", "Lusaka", "Harare"];
const colors = ["Alice blue", "Amaranth", "Amber", "Amethyst", "Apricot", "Aquamarine", "Azure", "Baby blue", "Beige", "Brick red", "Black", "Blue", "Blue - green", "Blue - violet", "Blush", "Bronze", "Brown", "Burgundy", "Byzantium", "Carmine", "Cerise", "Cerulean", "Champagne", "Chartreuse green", "Chocolate", "Cobalt blue", "Coffee", "Copper", "Coral", "Crimson", "Cyan", "Desert sand", "Electric blue", "Emerald", "Erin", "Gold", "Gray", "Green", "Harlequin", "Indigo", "Ivory", "Jade", "Jungle green", "Lavender", "Lemon", "Lilac", "Lime", "Magenta", "Magenta rose", "Maroon", "Mauve", "Navy blue", "Ochre", "Olive", "Orange", "Orange - red", "Orchid", "Peach", "Pear", "Periwinkle", "Persian blue", "Pink", "Plum", "Prussian blue", "Puce", "Purple", "Raspberry", "Red", "Red - violet", "Rose", "Ruby", "Salmon", "Sangria", "Sapphire", "Scarlet", "Silver", "Slate gray", "Spring bud", "Spring green", "Tan", "Taupe", "Teal", "Turquoise", "Ultramarine", "Violet", "Viridian", "White", "Yellow"];
const continents = ["Asia", "Africa", "Europe", "North America", "South America", "Australia", "Antartica"];
const countries = ["Afghanistan", "Albania", "Algeria", "Andorra", "Angola", "Antigua and Barbuda", "Argentina", "Armenia", "Australia", "Austria", "Azerbaijan", "Bahamas", "Bahrain", "Bangladesh", "Barbados", "Belarus", "Belgium", "Belize", "Benin", "Bhutan", "Bolivia", "Bosnia and Herzegovina", "Botswana", "Brazil", "Brunei", "Bulgaria", "Burkina Faso", "Burundi", "Côte d'Ivoire", "Cabo Verde", "Cambodia", "Cameroon", "Canada", "Central African Republic", "Chad", "Chile", "China", "Colombia", "Comoros", "Congo (Congo - Brazzaville)", "Costa Rica", "Croatia", "Cuba", "Cyprus", "Czechia (Czech Republic)", "Democratic Republic of the Congo", "Denmark", "Djibouti", "Dominica", "Dominican Republic", "Ecuador", "Egypt", "El Salvador", "Equatorial Guinea", "Eritrea", "Estonia", "Eswatini (fmr. Swaziland)", "Ethiopia", "Fiji", "Finland", "France", "Gabon", "Gambia", "Georgia", "Germany", "Ghana", "Greece", "Grenada", "Guatemala", "Guinea", "Guinea - Bissau", "Guyana", "HaitiHoly See", "Honduras", "Hungary", "Iceland", "India", "Indonesia", "Iran", "Iraq", "Ireland", "Israel", "Italy", "Jamaica", "Japan", "Jordan", "Kazakhstan", "Kenya", "Kiribati", "Kuwait", "Kyrgyzstan", "Laos", "Latvia", "Lebanon", "Lesotho", "Liberia", "Libya", "Liechtenstein", "Lithuania", "Luxembourg", "Madagascar", "Malawi", "Malaysia", "Maldives", "Mali", "Malta", "Marshall Islands", "Mauritania", "Mauritius", "Mexico", "Micronesia", "Moldova", "Monaco", "Mongolia", "Montenegro", "Morocco", "Mozambique", "Myanmar (formerly Burma)", "Namibia", "Nauru", "Nepal", "Netherlands", "New Zealand", "Nicaragua", "Niger", "Nigeria", "North Korea", "North Macedonia", "Norway", "Oman", "Pakistan", "Palau", "Palestine State", "Panama", "Papua New Guinea", "Paraguay", "Peru", "Philippines", "Poland", "Portugal", "Qatar", "Romania", "Russia", "Rwanda", "Saint Kitts and Nevis", "Saint Lucia", "Saint Vincent and the Grenadines", "Samoa", "San Marino", "Sao Tome and Princip", "Saudi Arabia", "Senegal", "Serbia", "Seychelles", "Sierra Leone", "Singapore", "Slovakia", "Slovenia", "Solomon Islands", "Somalia", "South Africa", "South Korea", "South Sudan", "Spain", "Sri Lanka", "Sudan", "Suriname", "Sweden", "Switzerland", "Syria", "Tajikistan", "Tanzania", "Thailand", "Timor - Leste", "Togo", "Tonga", "Trinidad and Tobago", "Tunisia", "Turkey", "Turkmenistan", "Tuvalu", "Uganda", "Ukraine", "United Arab Emirates", "United Kingdom", "United States of America", "Uruguay", "Uzbekistan", "Vanuatu", "Venezuela", "Vietnam", "Yemen", "Zambia", "Zimbabwe"];
const cryptoCurrencies = ["Bitcoin (BTC)", "Ethereum (ETH)", "Tether (USDT)", "USD Coin (USDC)", "BNB (BNB)", "XRP (XRP)", "Binance USD (BUSD)", "Cardano (ADA)", "Solana (SOL)", "Dogecoin (DOGE)", "Polkadot (DOT)", "Dai (DAI)", "Polygon (MATIC)", "Shiba Inu (SHIB)", "TRON (TRX)", "Avalanche (AVAX)", "Wrapped Bitcoin (WBTC)", "Uniswap (UNI)", "UNUS SED LEO (LEO)", "Cosmos (ATOM)", "Ethereum Classic (ETC)", "Chainlink (LINK)", "Litecoin (LTC)", "FTX Token (FTT)", "Stellar (XLM)", "Cronos (CRO)", "NEAR Protocol (NEAR)", "Algorand (ALGO)", "Monero (XMR)", "Bitcoin Cash (BCH)", "Flow (FLOW)", "ApeCoin (APE)", "VeChain (VET)", "Filecoin (FIL)", "Chiliz (CHZ)", "Toncoin (TON)", "Internet Computer (ICP)", "Hedera (HBAR)", "Terra Classic (LUNC)", "Quant (QNT)", "Tezos (XTZ)", "The Sandbox (SAND)", "Decentraland (MANA)", "EOS (EOS)", "Theta Network (THETA)", "Elrond (EGLD)", "Aave (AAVE)", "Axie Infinity (AXS)", "TrueUSD (TUSD)", "Bitcoin SV (BSV)", "Pax Dollar (USDP)", "OKB (OKB)", "KuCoin Token (KCS)", "Zcash (ZEC)", "eCash (XEC)", "IOTA (MIOTA)", "BitTorrent - New (BTT)", "The Graph (GRT)", "USDD (USDD)", "Huobi Token (HT)", "Maker (MKR)", "PancakeSwap (CAKE)", "Neutrino USD (USDN)", "Klaytn (KLAY)"];
const currencies = ["New Zealand dollar (NZD)", "Australian dollar (AUD)", "Singapore dollar (SGD)", "Brunei dollar (BND)", "Libyan dinar (LYD)", "Canadian dollar (CAD)", "United States dollar (USD)", "Swiss franc (CHF)", "Euro (EUR)", "Cayman Islands dollar (KYD)", "Gibraltar pound (GIP)", "Pound sterling (GBP)", "Jordan dinar (JOD)", "Omani rial (OMR)", "Bahrain dinar (BHD)", "Kuwaiti dinar (KWD)", "Japanese Yen (JPY)", "South African Rand (ZAR)"];
const daysOfWeek = ["Monday", "Tuesday", "Wednesday", "Thursday", "Friday", "Saturday", "Sunday"];
const firstNames = ["James", "Mary", "Robert", "Patricia", "John", "Jennifer", "Michael", "Linda", "David", "Elizabeth", "William", "Barbara", "Richard", "Susan", "Joseph", "Jessica", "Thomas", "Sarah", "Charles", "Karen", "Christopher", "Lisa", "Daniel", "Nancy", "Matthew", "Betty", "Anthony", "Margaret", "Mark", "Sandra", "Donald", "Ashley", "Steven", "Kimberly", "Paul", "Emily", "Andrew", "Donna", "Joshua", "Michelle", "Kenneth", "Carol", "Kevin", "Amanda", "Brian", "Dorothy", "George", "Melissa", "Timothy", "Deborah", "Ronald", "Stephanie", "Edward", "Rebecca", "Jason", "Sharon", "Jeffrey", "Laura", "Ryan", "Cynthia", "Jacob", "Kathleen", "Gary", "Amy", "Nicholas", "Angela", "Eric", "Shirley", "Jonathan", "Anna", "Stephen", "Brenda", "Larry", "Pamela", "Justin", "Emma", "Scott", "Nicole", "Brandon", "Helen", "Benjamin", "Samantha", "Samuel", "Katherine", "Gregory", "Christine", "Alexander", "Debra", "Frank", "Rachel", "Patrick", "Carolyn", "Raymond", "Janet", "Jack", "Catherine", "Dennis", "Maria", "Jerry", "Heather", "Tyler", "Diane", "Aaron", "Ruth", "Jose", "Julie", "Adam", "Olivia", "Nathan", "Joyce", "Henry", "Virginia", "Douglas", "Victoria", "Zachary", "Kelly", "Peter", "Lauren", "Kyle", "Christina", "Ethan", "Joan", "Walter", "Evelyn", "Noah", "Judith", "Jeremy", "Megan", "Christian", "Andrea", "Keith", "Cheryl", "Roger", "Hannah", "Terry", "Jacqueline", "Gerald", "Martha", "Harold", "Gloria", "Sean", "Teresa", "Austin", "Ann", "Carl", "Sara", "Arthur", "Madison", "Lawrence", "Frances", "Dylan", "Kathryn", "Jesse", "Janice", "Jordan", "Jean", "Bryan", "Abigail", "Billy", "Alice", "Joe", "Julia", "Bruce", "Judy", "Gabriel", "Sophia", "Logan", "Grace", "Albert", "Denise", "Willie", "Amber", "Alan", "Doris", "Juan", "Marilyn", "Wayne", "Danielle", "Elijah", "Beverly", "Randy", "Isabella", "Roy", "Theresa", "Vincent", "Diana", "Ralph", "Natalie", "Eugene", "Brittany", "Russell", "Charlotte", "Bobby", "Marie", "Mason", "Kayla", "Philip", "Alexis", "Louis", "Lori"];
const foodCategories = ["Fruit and vegetables", "Starchy food", "Dairy", "Protein", "Fat"];
const fruits = ["Apples", "Blueberries", "Bananas", "Oranges", "Dragon fruit", "Mango", "Avocado"];
const genders = ["male", "female"];
const hobbies = ["Chess", "Board games", "Video games", "Poker", "Card games", "Jigsaw puzzles", "Sudoku", "Crosswords", "Writing", "Blogging", "Podcasting", "Photography", "Travel", "Sports", "Yoga", "Dance", "Art", "Reading", "Making music", "Listening to music"];
const itJobTitles = ["Computer systems manager", "Network architect", "Systems analyst", "IT coordinator", "Network administrator", "Network engineer", "Service desk analyst", "System administrator", "Wireless network engineer", "Database administrator", "Database analyst", "Data quality manager", "Database report writer", "SQL database administrator", "Big data engineer / architect", "Business intelligence specialist / analyst", "Business systems analyst", "Data analyst", "Data analytics developer", "Data modeling analyst", "Data scientist", "Data warehouse manager", "Data warehouse programming specialist", "Intelligence specialist", "Back - end developer", "Cloud / software architect", "Cloud / software developer", "Cloud / software applications engineer", "Cloud system administrator", "Cloud system engineer", "DevOps engineer", "Front - end developer", "Full - stack developer", "Java developer", "Platform engineer", "Release manager", "Reliability engineer", "Software engineer", "Software quality assurance analyst", "UI (user interface) designer", "UX (user experience) designer", "Web developer", "Application security administrator", "Artificial intelligence security specialist", "Cloud security specialist", "Cybersecurity hardware engineer", "Cyberintelligence specialist", "Cryptographer", "Data privacy officer", "Digital forensics analyst", "IT security engineer", "Information assurance analyst", "Security systems administrator", "Help desk support specialist", "IT support specialist", "Customer service representative", "Technical product manager", "Product manager", "Project manager", "Program manager", "Portfolio manager"];
const itemConditions = ["New", "Open box", "Certified - Refurbished", "Excellent - Refurbished", "Very Good - Refurbished", "Good - Refurbished", "Seller refurbished", "Used", "For parts or not working"];
const jobCategories = ["Administration, business and management", "Alternative therapies", "Animals, land and environment", "Computing and ICT", "Construction and building", "Design, arts and crafts", "Education and training", "Engineering", "Facilities and property services", "Financial services", "Garage services", "Hairdressing and beauty", "Healthcare", "Heritage, culture and libraries", "Hospitality, catering and tourism", "Languages", "Legal and court services", "Manufacturing and production", "Performing arts and media", "Print and publishing, marketing and advertising", "Retail and customer services", "Science, mathematics and statistics", "Security, uniformed and protective services", "Social sciences and religion", "Social work and caring services", "Sport and leisure", "Transport, distribution and logistics"];
const languages = ["Brazilian Portuguese", "Canadian French", "English", "French Creole", "Haitian Creole", "Navajo", "Quechua", "Spanish", "Catalan", "Danish", "Dutch", "Faroese", "Finnish", "Flemish", "French", "German", "Greek", "Icelandic", "Italian", "Norwegian", "Portuguese", "Spanish", "Swedish", "Belarusian", "Bosnian", "Bulgarian", "Croatian", "Czech", "Estonian", "Hungarian", "Latvian", "Lithuanian", "Macedonian", "Polish", "Romanian", "Russian", "Serbian", "Slovak", "Slovenian", "Turkish", "Ukrainian", "Amharic (Ethiopia)", "Dinka (Sudan)", "Ibo (Nigeria)", "Kirundi", "Mandinka", "Nuer (Nilo - Saharan)", "Oromo (Ethiopia)", "Kinyarwanda", "Shona (Zimbabwe)", "Somali", "Swahili", "Tigrigna (Ethiopia)", "Wolof", "Xhosa", "Yoruba", "Zulu", "Arabic", "Dari", "Farsi", "Hebrew", "Kurdish", "Pashtu", "Punjabi", "Urdu(Pakistan)", "Armenian", "Azerbaijani", "Georgian", "Kazakh", "Mongolian", "Turkmen", "Uzbek"];
const lastNames = ["Smith", "Johnson", "Williams", "Brown", "Jones", "Garcia", "Miller", "Davis", "Rodriguez", "Martinez", "Hernandez", "Lopez", "Gonzalez", "Wilson", "Anderson", "Thomas", "Taylor", "Moore", "Jackson", "Martin", "Lee", "Perez", "Thompson", "White", "Harris", "Sanchez", "Clark", "Ramirez", "Lewis", "Robinson", "Walker", "Young", "Allen", "King", "Wright", "Scott", "Torres", "Nguyen", "Hill", "Flores", "Green", "Adams", "Nelson", "Baker", "Hall", "Rivera", "Campbell", "Mitchell", "Carter", "Roberts"];
const letters = ["A", "B", "C", "D", "E", "F", "G", "H", "I", "J", "K", "L", "M", "N", "O", "P", "Q", "R", "S", "T", "U", "V", "W", "X", "Y", "Z"];
const monthsOfYear = ["January", "February", "March", "April", "May", "June", "July", "August", "September", "October", "November", "December"];
const mountains = ["Himalayas", "Karakoram", "Hindu Kush", "Kongur Shan", "Daxue Mountains", "Pamir Mountain", "Kakshaal Too", "Nyenchen Tanglha", "Andes", "Kunlun Mountains", "Cordillera de la Ramada", "Tian Shan", "Hindu Raj", "Cordillera Occidental", "Alaska Range", "Saint Elias Mountains", "Eastern Rift mountains", "Sierra Nevada de Santa Marta", "Caucasus Mountains", "Trans - Mexican Volcanic Belt", "Alborz", "Yun Range", "Bogda Shan", "Cordillera Oriental", "Armenian Highlands", "Rwenzori Mountains", "Wrangell Mountains", "Sierra Nevada de Mérida", "Trans - Ili Alatau", "Sentinel Range", "Sudirman Range", "Alps", "Kamchatka", "Semien Mountains", "Bismarck Range", "Virunga Mountains", "Altai Mountains", "Sierra Nevada", "Sawatch Range (Rocky Mountains)", "Cascade Range", "Sierra Madre de Chiapas", "Atlas Mountains", "Finisterre Range", "Crocker Range, Borneo", "Cameroon line", "Coast Mountains", "Chugach Mountains", "Canadian Rockies", "Yushan Range", "Baluchestan Mountains", "Saur Mountain", "Patkai", "Cordillera de Talamanca", "Barisan Mountains, Sumatra", "Ross Island", "Honshu", "Southern Alps", "Tenerife", "Watkins Range", "Tengger Range", "Owen Stanley Range", "Sarawat Mountains", "Sredinny Range", "Sierra Nevada", "Latimojong", "Tibesti Mountains", "Pyrenees", "Sicily", "Siple Island", "Cordillera Central, Hispaniola", "Réunion", "Al Hajar Mountains", "Cerro de la Neblina", "Douglas Range, Alexander", "Timor", "Apo-Talomo, Mindanao", "Allardyce Range", "Cordillera Central, Luzon", "Madagascar", "Aleutian Range", "Fogo"];
const movieGenres = ["Action", "Adventure", "Comedy", "Crime and mystery", "Fantasy", "Historical", "Horror", "Romance", "Satire", "Science fiction", "Speculative", "Thriller", "Western"];
const musicGenres = ["Pop", "Hip hop", "Rock", "Rhythm and blues", "Soul", "Reggae", "Country", "Funk", "Folk", "Jazz", "Disco", "Classical", "Electronic", "Latino", "Blues", "New Age", "Vocal", "Christian", "Ska", "Traditional"];
const oceans = ["Pacific Ocean", "Atlantic Ocean", "Indian Ocean", "Southern Ocean", "Arctic Ocean"];
const os = ["MS Windows", "Ubuntu", "Mac OS", "Fedora", "Solaris", "Free BSD", "Chrome OS"];
const planets = ["Mercury", "Venus", "Earth", "Mars", "Jupiter", "Saturn", "Uranus", "Neptune"];
const programmingLanguages = ["Javascript", "Python", "Go", "Java", "Kotlin", "PHP", "C#", "Swift", "R", "Ruby", "C and C++", "Matlab", "Typescript", "Scala"];
const quotesLatin = ["Pulvis et umbra sumus.", "humani nihil a me alienum puto.", "Fiat Lux.", "Labor omnia vincit.", "De malo, bonum.", "Omne bonum a Deo, omne malum ab homine.", "Nota res mala, optima.", "Ars longa, vita brevis.", "Omnis cum in tenebris praesertim vita laboret.", "Sic vita fluit, dum stare videtur.", "Vivamus, moriendum est.", "Mors ultima ratio.", "Mors certa, hora incerta.", "Non omnis moriar.", "Omnes una manet nox.", "Tantum religio potuit suadere malorum.", "Deus vult.", "Permitte divis cetera.", "Deos fortioribus adesse.", "Cito fit quod dii volunt.", "In primis venerare Deos.", "Vocatus atque non vocatus, Deus aderit.", "Video meliora, proboque, deteriora sequor.", "Rex non potest peccare.", "Abusus non tollit usum.", "Ora et Labora.", "Credo quia absurdum.", "Quod semper, quod ubique, quo ab omnibus.", "Flectere si nequeo superos, Acheronta movebo.", "Vada retro me, Satana.", "Omne ignotum pro magnifico.", "Vi Veri Veniversum Vivus Vici.", "Vitam impendere vero.", "Sic transit gloria mundi.", "Et in Arcadia ego.", "Tempus edax rerum.", "Omnes vulnerant, ultima necat.", "Ex hoc momento pendet aeternitas.", "Fugit inreparabile tempus.", "Serius est quam cogitas.", "Lente hora, celeriter anni.", "In saecula saeculorum.", "Exegi monumentum aere perennius.", "Caelesti sumus omnes semine oriundi.", "Veritas odit moras.", "Lente hora, celeriter anni.", "Si post fata venit gloria, non propero.", "Potius sero quam numquam.", "Bis dat, qui dat celeriter.", "Plaudite, amici, comedia finita est!", "Finis coronat opus.", "Omnes vulnerant, ultima necat.", "Quod nocet, saepe docet.", "Fas est ab hoste doceri.", "Quae nocent, saepe docent.", "Qui dormit, non peccat.", "Natura abhorret a vacua.", "Aut viam inveniam aut faciam.", "Via trita, via tuta.", "Omnium rerum principia parva sunt.", "Novus ordo seclorum.", "Quot homines tot sententiae: suus cuique mos.", "Canis caninam non est.", "Si parva licet componere magnis.", "Summum jus, summa injuria.", "Ubi bene, ibi patria.", "Abusus non tollit usum.", "Memento mori.", "Nil homini certum est.", "Umbra sicut hominis vita.", "Et in Arcadia ego.", "Semper idem.", "Quinon proficit deficit.", "Nihil sub sole novum.", "Exceptio probat regulam de rebus non exceptis."];
const religions = ["Judaism", "Christianity", "Islam", "Hinduism", "Buddhism", "Confucianism", "Taoism"];
const schoolGradesLettered = ["A", "B", "C", "D", "E", "F"];
const schoolGradesNumbered = [1, 2, 3, 4, 5];
const schoolSubjects = ["Reading", "Language arts", "Speech and Debate", "English", "Basic Math", "Pre - algebra", "Consumer Math", "Algebra", "Geometry", "Honors Math in Algebra or Geometry", "Life Science", "Earth Science", "Physical Science", "Health", "Social Studies", "Geography", "Ancient Civilizations", "Medieval and Renaissance", "U.S. History and Government", "French / Spanish / Latin", "Computer Science or Lab", "Art", "Home Economics", "Woodshop", "Metal Shop", "Business Technology", "Instrumental Music", "Band", "Choir", "Drama", "Physical Education", "Sports", "Special Education Day Class", "Resource Program", "Speech Therapy", "Occupational Therapy"];
const sizes = ["XXS", "XS", "S", "M", "L", "XL", "XXL", "3XL", "4XL", "5XL", "6XL", "7XL"];
const skillLevels = ["Novice", "Advanced Beginner", "Competent", "Proficient", "Expert"];
const todos = ["Shopping", "Practice", "Pick up children", "Cook dinner", "Prepare guesthouse", "Appointment", "Dentist appointment", "Finish project", "Start project", "Write down ideas about new project", "Deploy application", "Notify all users about the application change", "Prepare for the trip", "Wash hair", "Wash car", "Brush teeth", "Clean the house", "Prepare for the big event", "Prepare for the hike", "Visit family", "School reunion", "Family reunion", "Buy sweets for children", "Buy bread", "Buy grocery", "Practice grammar", "Work out", "Sign up for the new course", "Wash dishes", "Practice Latin vocabulary", "Read that new book", "Buy book about fungi", "Practice algebra", "Practice math", "Learn German irregular verbs", "Get info about astronomy", "Buy course about programming", "Go on the bike ride", "Find lost keys", "Fix car", "Fix bike", "Fix bicycle", "Buy shoes", "Paint walls", "Practice yoga", "Get children from the park", "Buy new tools", "Fix broken tools", "Call barbara", "Call Steve", "Call Jessica", "Call aunt Agatha", "Make appointment"];
const vegetables = ["Carrots", "Potato", "Tomato", "Onions", "Broccoli", "Mushroom", "Lettuce", "Capsicum"];
const words = ["high", "every", "near", "add", "food", "between", "own", "below", "country", "plant", "last", "school", "father", "keep", "tree", "never", "start", "city", "earth", "eye", "light", "thought", "head", "under", "story", "Words", "saw", "left", "few", "while", "along", "might", "close", "something", "seem", "next", "hard", "open", "example", "begin", "life", "always", "those", "both", "paper", "together", "got", "group", "often", "run", "Words", "important", "until", "children", "side", "feet", "car", "mile", "night", "walk", "white", "sea", "began", "grow", "took", "river", "four", "carry", "state", "once", "book", "hear", "stop", "without", "second", "later", "Words", "miss", "idea", "enough", "eat", "face", "watch", "far", "Indian", "really", "almost", "let", "above", "girl", "sometimes", "mountain", "cut", "young", "talk", "soon", "list", "song", "being", "leave", "family", "over", "new", "sound", "take", "only", "little", "work", "know", "place", "year", "live", "me", "back", "give", "most", "very", "after", "thing", "our", "just", "name", "good", "sentence", "man", "think", "Words", "say", "great", "where", "help", "through", "much", "before", "line", "right", "too", "mean", "old", "any", "same", "tell", "boy", "follow", "came", "want", "show", "also", "around", "form", "three", "small", "Words", "set", "put", "end", "does", "another", "well", "large", "must", "big", "even", "such", "because", "turn", "here", "why", "ask", "went", "men", "read", "need", "land", "different", "home", "us", "move", "Words", "try", "kind", "hand", "picture", "again", "change", "off", "play", "spell", "air", "away", "animal", "house", "point", "page", "letter", "mother", "answer", "found", "study", "still", "learn", "should", "America", "world"];
const writers = ["Gabriel Garcia Marquez", "Robert Harris", "Ralph Ellison", "Giles Coren", "Julie Burchill", "Joseph Freiherr von Eichendorff", "Martin Amis", "E.B.White", "John Milton", "Giuseppe Tomasi di Lampedusa", "Michael Azerrad", "J.K.Rowling", "Richard Littlejohn", "Thomas Mann", "David Berman", "Bret Easton Ellis", "Gary Snyder", "Philip K.Dick", "Peter Cook", "Jorge Luis Borges", "Pablo Neruda", "Suetonius", "Arthur Rimbaud", "Gore Vidal", "Jane Austen", "Francis Bacon", "James Thurber", "Iris Murdoch", "Evelyn Waugh", "Saul Bellow", "Marcel Proust", "Wole Soyinka", "J.R.R.Tolkien", "Don DeLillo", "Richard Yates", "John Updike", "Virginia Woolf", "Joseph Conrad", "Cormac McCarthy", "Primo Levi", "James Baldwin", "William Shakespeare", "Woody Allen", "Leo Tolstoy", "George Eliot", "Homer", "J.D.Salinger", "F.Scott Fitzgerald", "Charles Dickens", "Ivan Turgenev", "John Donne"];
const zodiacSigns = ["Aries", "Taurus", "Gemini", "Cancer", "Leo", "Virgo", "Libra", "Scorpio", "Saggitarius", "Capricorn", "Aquarius", "Pisces"];

module.exports = {
  actors,
  artists,
  browsers,
  cities,
  colors,
  continents,
  countries,
  cryptoCurrencies,
  currencies,
  daysOfWeek,
  firstNames,
  foodCategories,
  fruits,
  genders,
  hobbies,
  itJobTitles,
  itemConditions,
  jobCategories,
  languages,
  lastNames,
  letters,
  monthsOfYear,
  mountains,
  movieGenres,
  musicGenres,
  oceans,
  os,
  planets,
  programmingLanguages,
  quotesLatin,
  religions,
  schoolGradesLettered,
  schoolGradesNumbered,
  schoolSubjects,
  sizes,
  skillLevels,
  todos,
  vegetables,
  words,
  writers,
  zodiacSigns
}
