const actors = ["Johnny Depp", "Al Pacino", "Robert De Niro", "Kevin Spacey", "Denzel Washington", "Russell Crowe", "Brad Pitt", "Angelina Jolie", "Leonardo DiCaprio", "Tom Cruise", "John Travolta", "Arnold Schwarzenegger", "Sylvester Stallone", "Kate Winslet", "Christian Bale", "Morgan Freeman", "Keanu Reeves", "Nicolas Cage", "Hugh Jackman", "Edward Norton", "Bruce Willis", "Tom Hanks", "Charlize Theron", "Will Smith", "Sean Connery", "Keira Knightley", "Vin Diesel", "Matt Damon", "Richard Gere", "Catherine Zeta - Jones", "Clive Owen", "Mel Gibson", "George Clooney", "Jack Nicholson", "Scarlett Johansson", "Tom Hardy", "Robert Downey Jr.", "Orlando Bloom", "Ian McKellen", "Antonio Banderas", "Guy Pearce", "Samuel L.Jackson", "Sandra Bullock", "Meg Ryan", "Megan Fox", "Nicole Kidman", "Gerard Butler", "Simon Baker", "Cameron Diaz", "Katherine Heigl"];
const animals = ["Ant", "Antelope", "Baboon", "Bat", "Beagle", "Bear", "Bird", "Butterfly", "Cat", "Caterpillar", "Chicken", "Cow", "Dog", "Dolphin", "Donkey", "Eagle", "Fish", "Fly", "Fox", "Frog", "Gerbil", "Goose", "Gopher", "Gorilla", "Heron", "Honey Bee", "Horn Shark", "Horse", "Ibis", "Iguana", "Impala", "Jackal", "Jaguar", "Javanese", "Jellyfish", "Kakapo", "Kangaroo", "King Penguin", "Kiwi", "Koala", "Lemming", "Lemur", "Leopard", "Saola", "Scorpion", "Snake", "Swan", "Tuatara", "Turkey", "Zebra"];
const artists = ["Rihanna", "Drake", "Coldplay", "Eminem", "Maroon", "Ed Sheeran", "Bruno Mars", "Kanye West", "The Weeknd", "Adele", "Beyoncé", "U2", "Justin Bieber", "Taylor Swift", "Kendrick Lamar", "Katy Perry", "Red Hot Chili Peppers", "Calvin Harris", "Nicki Minaj", "Lil Wayne", "Imagine Dragons", "Lady Gaga", "Chris Brown", "David Guetta", "Ariana Grande", "Lana Del Rey", "Queen", "Justin Timberlake", "The Killers", "Wiz Khalifa", "Usher", "Radiohead", "Arctic Monkeys", "Kings of Leon", "Post Malone", "Ellie Goulding", "Pitbull", "Green Day", "J.Cole", "Black Eyed Peas", "Muse", "Miley Cyrus", "Jason Derulo", "Mumford & Sons", "Sia", "The Rolling Stones", "Metallica", "Sam Smith", "A$AP Rocky", "Fleetwood Mac"];
const bands = ["Elvis Presley", "The Beatles", "The Rolling Stones", "The Who", "Aerosmith", "Bon Jovi", "Van Halen", "Journey", "Eagles", "Def Leppard", "The Clash", "Bruce Springsteen", "Boston", "Led Zeppelin", "Lynyrd Skynyrd", "Tom Petty", "Pink Floyd", "Mötley Crüe", "Whitesnake", "Steppenwolf", "Scorpions", "KISS", "Elton John", "Creedence Clearwater Revival", "Queensrÿche", "Guns n' Roses", "Dokken", "Bad Company", "U2", "Steve Miller Band", "The Kinks", "Deep Purple", "Badfinger", "Coldplay", "AC / DC", "Green Day", "Eddie Money", "Meat Loaf", "Doors Down", "Poison"];
const books = ["In Search of Lost Time by Marcel Proust", "Ulysses by James Joyce", "Don Quixote by Miguel de Cervantes", "One Hundred Years of Solitude by Gabriel Garcia Marquez", "The Great Gatsby by F.Scott Fitzgerald", "Moby Dick by Herman Melville", "War and Peace by Leo Tolstoy", "Hamlet by William Shakespeare", "The Odyssey by Homer", "Madame Bovary by Gustave Flaubert", "The Divine Comedy by Dante Alighieri", "Lolita by Vladimir Nabokov", "The Brothers Karamazov by Fyodor Dostoyevsky", "Crime and Punishment by Fyodor Dostoyevsky", "Wuthering Heights by Emily Brontë", "The Catcher in the Rye by J.D.Salinger", "Pride and Prejudice by Jane Austen", "The Adventures of Huckleberry Finn by Mark Twain", "Anna Karenina by Leo Tolstoy", "Alice's Adventures in Wonderland by Lewis Carroll", "The Iliad by Homer", "To the Lighthouse by Virginia Woolf", "Catch - 22 by Joseph Heller", "Heart of Darkness by Joseph Conrad", "The Sound and the Fury by William Faulkner", "Nineteen Eighty Four by George Orwell", "Great Expectations by Charles Dickens", "One Thousand and One Nights by India / Iran / Iraq / Egypt", "The Grapes of Wrath by John Steinbeck", "Absalom, Absalom! by William Faulkner", "Invisible Man by Ralph Ellison", "To Kill a Mockingbird by Harper Lee", "The Trial by Franz Kafka", "The Red and the Black by Stendhal", "Middlemarch by George Eliot", "Gulliver's Travels by Jonathan Swift", "Beloved by Toni Morrison", "Mrs.Dalloway by Virginia Woolf", "The Stories of Anton Chekhov by Anton Chekhov", "The Stranger by Albert Camus", "Jane Eyre by Charlotte Bronte", "The Aeneid by Virgil", "Collected Fiction by Jorge Luis Borges", "The Sun Also Rises by Ernest Hemingway", "David Copperfield by Charles Dickens", "Tristram Shandy by Laurence Sterne", "Leaves of Grass by Walt Whitman", "The Magic Mountain by Thomas Mann", "A Portrait of the Artist as a Young Man by James Joyce", "Midnight's Children by Salman Rushdie "];
const browsers = ["Firefox", "Google Chrome", "Microsoft Edge", "Apple Safari", "Opera", "Brave", "Vivaldi", "DuckDuckgo"];
const cars = ["1994 Audi RS2", "2011 Vauxhall Ampera", "2010 Dacia Duster", "2003 Lamborghini Gallardo", "1998 Honda Integra Type R", "1999 BMW X5", "2011 Ferrari FF", "2005 Mazda MX - 5", "2009 Alfa Romeo 8C Spider", "2004 Ford GT", "1998 Fiat Multipla", "2013 Jaguar F - Type V6S", "2008 Mercedes - Benz CLK Black", "2012 Toyota GT86", "1996 Ferrari 550", "1993 Lancia Delta Integrale Evo III", "1995 BMW 5 - Series E39", "1996 Lotus Elise", "2004 Porsche Carrera GT", "2002 Ferrari Enzo", "2009 Aston Martin V12 Vantage", "2012 McLaren 12C Spider", "2007 Fiat 500", "2004 Land Rover Discovery", "2005 Mercedes - Benz S - Class", "1998 Audi TT", "2003 Bentley Continental GT", "1999 Audi A2", "1997 Toyota Hilux", "1999 Honda S2000", "2009 Lamborghini Murcielago LP - 670SV", "2012 Range Rover", "2000 Ariel Atom", "1999 Pagani Zonda", "1999 Subaru Impreza P1", "2000 Mitsubishi Evo VI Makinen", "2012 Ford Fiesta ST", "2008 Nissan GT - R", "2001 Mini Cooper", "2004 Toyota Prius", "2010 Lexus LFA", "1993 Renault Clio Williams", "1993 Porsche 911 993", "1998 Ford Focus", "1999 BMW 320d", "1996 Porsche Boxster", "2009 Ferrari 458", "2003 Rolls Royce Phantom", "2005 VW Golf GTI", "2005 Bugatti Veyron"];
const cats = ["Abyssinian", "American Bobtail", "American Curl", "American Shorthair", "Balinese", "Bengal", "Birman", "Bombay", "British Shorthair", "Burmese", "Burmilla", "Chartreux", "Chausie", "Colorpoint Shorthair", "Cornish Rex", "Devon Rex", "Egyptian Mau", "European Burmese", "Exotic Shorthair", "Havana Brown", "Himalayan", "Japanese Bobtail", "Khao Manee", "Korat", "LaPerm", "Lykoi", "Maine Coon", "Manx", "Norwegian Forest Cat", "Ocicat", "Persian", "Pixiebob", "Ragdoll", "Savannah", "Scottish Fold", "Selkirk Rex", "Serengeti", "Siamese", "Siberian", "Singapura", "Somali", "Sphynx", "Tonkinese", "Toyger", "Turkish Angora"];
const chemicalElements = ["Actinium (Ac)", "Aluminum (Al)", "Americium (Am)", "Antimony (Sb)", "Argon (Ar)", "Arsenic (As)", "Astatine (At)", "Barium (Ba)", "Berkelium (Bk)", "Beryllium (Be)", "Bismuth (Bi)", "Bohrium (Bh)", "Boron (B)", "Bromine (Br)", "Cadmium (Cd)", "Calcium (Ca)", "Californium (Cf)", "Carbon (C)", "Cerium (Ce)", "Cesium (Cs)", "Chlorine (Cl)", "Chromium (Cr)", "Cobalt (Co)", "Copernicium (Cn)", "Copper (Cu)", "Curium (Cm)", "Darmstadtium (Ds)", "Dubnium (Db)", "Dysprosium (Dy)", "Einsteinium (Es)", "Erbium (Er)", "Europium (Eu)", "Fermium (Fm)", "Flerovium (Fl)", "Fluorine (F)", "Francium (Fr)", "Gadolinium (Gd)", "Gallium (Ga)", "Germanium (Ge)", "Gold (Au)", "Hafnium (Hf)", "Hassium (Hs)", "Helium (He)", "Holmium (Ho)", "Hydrogen (H)", "Indium (In)", "Iodine (I)", "Iridium (Ir)", "Iron (Fe)", "Krypton (Kr)", "Lanthanum (La)", "Lawrencium (Lr)", "Lead (Pb)", "Lithium (Li)", "Livermorium (Lv)", "Lutetium (Lu)", "Magnesium (Mg)", "Manganese (Mn)", "Meitnerium (Mt)", "Mendelevium (Md)", "Mercury (Hg)", "Molybdenum (Mo)", "Moscovium (Mc)", "Neodymium (Nd)", "Neon (Ne)", "Neptunium (Np)", "Nickel (Ni)", "Nihonium (Nh)", "Niobium (Nb)", "Nitrogen (N)", "Nobelium (No)", "Oganesson (Og)", "Osmium (Os)", "Oxygen (O)", "Palladium (Pd)", "Phosphorus (P)", "Platinum (Pt)", "Plutonium (Pu)", "Polonium (Po)", "Potassium (K)", "Praseodymium (Pr)", "Promethium (Pm)", "Protactinium (Pa)", "Radium (Ra)", "Radon (Rn)", "Rhenium (Re)", "Rhodium (Rh)", "Roentgenium (Rg)", "Rubidium (Rb)", "Ruthenium (Ru)", "Rutherfordium (Rf)", "Samarium (Sm)", "Scandium (Sc)", "Seaborgium (Sg)", "Selenium (Se)", "Silicon (Si)", "Silver (Ag)", "Sodium (Na)", "Strontium (Sr)", "Sulfur (S)", "Tantalum (Ta)", "Technetium (Tc)", "Tellurium (Te)", "Tennessine (Ts)", "Terbium (Tb)", "Thallium (Tl)", "Thorium (Th)", "Thulium (Tm)", "Tin (Sn)", "Titanium (Ti)", "Tungsten (W)", "Uranium (U)", "Vanadium (V)", "Xenon (Xe)", "Ytterbium (Yb)", "Yttrium (Y)", "Zinc (Zn)", "Zirconium (Zr)"];
const chessPlayers = ["Magnus Carlsen", "Ding Liren", "Ian Nepomniachtchi", "Alireza Firouzja", "Wesley So", "Hikaru Nakamura", "Anish Giri", "Fabiano Caruana", "Viswanathan Anand", "Levon Aronian", "Richard Rapport", "Sergey Karjakin", "Maxime Vachier - Lagrave", "Leinier Dominguez Perez", "Shakhriyar Mamedyarov", "Teimour Radjabov", "Alexander Grischuk", "Arjun Erigaisi", "Jan - Krzysztof Duda", "Dmitry Andreikin", "Veselin Topalov", "Le Quang Liem", "Nikita Vitiugov", "Wang Hao", "Parham Maghsoodloo", "Yu Yangyi", "Pentala Harikrishna", "Francisco Vallejo Pons", "Nodirbek Abdusattorov", "Samuel Shankland", "Gabriel Sargissian", "Vidit Santosh Gujrathi", "Sanan Sjugirov", "Daniil Dubov", "Kirill Alekseenko", "Bu Xiangzhi", "Bogdan - Daniel Deac", "Vladislav Artemiev", "Hans Moke Niemann", "Evgeny Tomashevsky", "Pavel Eljanov", "Vincent Keymer", "Michael Adams", "Radoslaw Wojtaszek", "Jorden van Foreest", "Matthew D Sadler", "Anton Korobov", "Jeffery Xiong", "Bobby Fischer", "Anatoly Karpov", "Viktor Korchnoi", "Boris Spassky", "Bent Larsen", "Mikhail Tal", "Lajos Portisch", "Tigran Petrosian", "Lev Polugaevsky", "Henrique Mecking", "Mikhail Botvinnik", "Lubomir Kavalek", "Jan Timman", "Vassily Smyslov", "Leonid Stein", "Ljubomir Ljubojević", "Efim Geller", "Vlastimil Hort", "Paul Keres", "Robert Hübner", "Jan Smejkal"];
const cities = ["Kabul", "Tirana (Tirane)", "Algiers", "Andorra la Vella", "Luanda", "Saint John's", "Buenos Aires", "Yerevan", "Canberra", "Vienna", "Baku", "Nassau", "Manama", "Dhaka", "Bridgetown", "Minsk", "Brussels", "Belmopan", "Porto Novo", "Thimphu", "La Paz", "Sarajevo", "Gaborone", "Brasilia", "Bandar Seri Begawan", "Sofia", "Ouagadougou", "Gitega", "Phnom Penh", "Yaounde", "Ottawa", "Praia", "Bangui", "N'Djamena", "Santiago", "Beijing", "Bogota", "Moroni", "Kinshasa", "Brazzaville", "San Jose", "Yamoussoukro", "Zagreb", "Havana", "Nicosia", "Prague", "Copenhagen", "Djibouti", "Roseau", "Santo Domingo", "Dili", "Quito", "Cairo", "San Salvador", "London", "Malabo", "Asmara", "Tallinn", "Mbabana", "Addis Ababa", "Palikir", "Suva", "Helsinki", "Paris", "Libreville", "Banjul", "Tbilisi", "Berlin", "Accra", "Athens", "Saint George's", "Guatemala City", "Conakry", "Bissau", "Georgetown", "Port au Prince", "Tegucigalpa", "Budapest", "Reykjavik", "New Delhi", "Jakarta", "Tehran", "Baghdad", "Dublin", "Jerusalem", "Rome", "Kingston", "Tokyo", "Amman", "Nur - Sultan", "Nairobi", "Tarawa Atoll", "Pristina", "Kuwait City", "Bishkek", "Vientiane", "Riga", "Beirut", "Maseru", "Monrovia", "Tripoli", "Vaduz", "Vilnius", "Luxembourg", "Antananarivo", "Lilongwe", "Kuala Lumpur", "Male", "Bamako", "Valletta", "Majuro", "Nouakchott", "Port Louis", "Mexico City", "Chisinau", "Monaco", "Ulaanbaatar", "Podgorica", "Rabat", "Maputo", "Nay Pyi Taw", "Windhoek", "Kathmandu", "Amsterdam", "Wellington", "Managua", "Niamey", "Abuja", "Pyongyang", "Skopje", "Belfast", "Oslo", "Muscat", "Islamabad", "Melekeok", "Panama City", "Port Moresby", "Asuncion", "Lima", "Manila", "Warsaw", "Lisbon", "Doha", "Bucharest", "Moscow", "Kigali", "Basseterre", "Castries", "Kingstown", "Apia", "San Marino", "Sao Tome", "Riyadh", "Edinburgh", "Dakar", "Belgrade", "Victoria", "Freetown", "Singapore", "Bratislava", "Ljubljana", "Honiara", "Mogadishu", "Cape Town", "Seoul", "Juba", "Madrid", "Sri Jayawardenapura Kotte", "Khartoum", "Paramaribo", "Stockholm", "Bern", "Damascus", "Taipei", "Dushanbe", "Dodoma", "Bangkok", "Lome", "Nuku'alofa", "Port of Spain", "Tunis", "Ankara", "Ashgabat", "Funafuti", "Kampala", "Kiev", "Abu Dhabi", "London", "Washington D.C.", "Montevideo", "Tashkent", "Port Vila", "Vatican City", "Caracas", "Hanoi", "Cardiff", "Sana'a", "Lusaka", "Harare"];
const colors = ["Alice blue", "Amaranth", "Amber", "Amethyst", "Apricot", "Aquamarine", "Azure", "Baby blue", "Beige", "Brick red", "Black", "Blue", "Blue - green", "Blue - violet", "Blush", "Bronze", "Brown", "Burgundy", "Byzantium", "Carmine", "Cerise", "Cerulean", "Champagne", "Chartreuse green", "Chocolate", "Cobalt blue", "Coffee", "Copper", "Coral", "Crimson", "Cyan", "Desert sand", "Electric blue", "Emerald", "Erin", "Gold", "Gray", "Green", "Harlequin", "Indigo", "Ivory", "Jade", "Jungle green", "Lavender", "Lemon", "Lilac", "Lime", "Magenta", "Magenta rose", "Maroon", "Mauve", "Navy blue", "Ochre", "Olive", "Orange", "Orange - red", "Orchid", "Peach", "Pear", "Periwinkle", "Persian blue", "Pink", "Plum", "Prussian blue", "Puce", "Purple", "Raspberry", "Red", "Red - violet", "Rose", "Ruby", "Salmon", "Sangria", "Sapphire", "Scarlet", "Silver", "Slate gray", "Spring bud", "Spring green", "Tan", "Taupe", "Teal", "Turquoise", "Ultramarine", "Violet", "Viridian", "White", "Yellow"];
const continents = ["Asia", "Africa", "Europe", "North America", "South America", "Australia", "Antartica"];
const countries = ["Afghanistan", "Albania", "Algeria", "Andorra", "Angola", "Antigua and Barbuda", "Argentina", "Armenia", "Australia", "Austria", "Azerbaijan", "Bahamas", "Bahrain", "Bangladesh", "Barbados", "Belarus", "Belgium", "Belize", "Benin", "Bhutan", "Bolivia", "Bosnia and Herzegovina", "Botswana", "Brazil", "Brunei", "Bulgaria", "Burkina Faso", "Burundi", "Côte d'Ivoire", "Cabo Verde", "Cambodia", "Cameroon", "Canada", "Central African Republic", "Chad", "Chile", "China", "Colombia", "Comoros", "Congo (Congo - Brazzaville)", "Costa Rica", "Croatia", "Cuba", "Cyprus", "Czechia (Czech Republic)", "Democratic Republic of the Congo", "Denmark", "Djibouti", "Dominica", "Dominican Republic", "Ecuador", "Egypt", "El Salvador", "Equatorial Guinea", "Eritrea", "Estonia", "Eswatini (fmr. Swaziland)", "Ethiopia", "Fiji", "Finland", "France", "Gabon", "Gambia", "Georgia", "Germany", "Ghana", "Greece", "Grenada", "Guatemala", "Guinea", "Guinea - Bissau", "Guyana", "HaitiHoly See", "Honduras", "Hungary", "Iceland", "India", "Indonesia", "Iran", "Iraq", "Ireland", "Israel", "Italy", "Jamaica", "Japan", "Jordan", "Kazakhstan", "Kenya", "Kiribati", "Kuwait", "Kyrgyzstan", "Laos", "Latvia", "Lebanon", "Lesotho", "Liberia", "Libya", "Liechtenstein", "Lithuania", "Luxembourg", "Madagascar", "Malawi", "Malaysia", "Maldives", "Mali", "Malta", "Marshall Islands", "Mauritania", "Mauritius", "Mexico", "Micronesia", "Moldova", "Monaco", "Mongolia", "Montenegro", "Morocco", "Mozambique", "Myanmar (formerly Burma)", "Namibia", "Nauru", "Nepal", "Netherlands", "New Zealand", "Nicaragua", "Niger", "Nigeria", "North Korea", "North Macedonia", "Norway", "Oman", "Pakistan", "Palau", "Palestine State", "Panama", "Papua New Guinea", "Paraguay", "Peru", "Philippines", "Poland", "Portugal", "Qatar", "Romania", "Russia", "Rwanda", "Saint Kitts and Nevis", "Saint Lucia", "Saint Vincent and the Grenadines", "Samoa", "San Marino", "Sao Tome and Princip", "Saudi Arabia", "Senegal", "Serbia", "Seychelles", "Sierra Leone", "Singapore", "Slovakia", "Slovenia", "Solomon Islands", "Somalia", "South Africa", "South Korea", "South Sudan", "Spain", "Sri Lanka", "Sudan", "Suriname", "Sweden", "Switzerland", "Syria", "Tajikistan", "Tanzania", "Thailand", "Timor - Leste", "Togo", "Tonga", "Trinidad and Tobago", "Tunisia", "Turkey", "Turkmenistan", "Tuvalu", "Uganda", "Ukraine", "United Arab Emirates", "United Kingdom", "United States of America", "Uruguay", "Uzbekistan", "Vanuatu", "Venezuela", "Vietnam", "Yemen", "Zambia", "Zimbabwe"];
const cryptoCurrencies = ["Bitcoin (BTC)", "Ethereum (ETH)", "Tether (USDT)", "USD Coin (USDC)", "BNB (BNB)", "XRP (XRP)", "Binance USD (BUSD)", "Cardano (ADA)", "Solana (SOL)", "Dogecoin (DOGE)", "Polkadot (DOT)", "Dai (DAI)", "Polygon (MATIC)", "Shiba Inu (SHIB)", "TRON (TRX)", "Avalanche (AVAX)", "Wrapped Bitcoin (WBTC)", "Uniswap (UNI)", "UNUS SED LEO (LEO)", "Cosmos (ATOM)", "Ethereum Classic (ETC)", "Chainlink (LINK)", "Litecoin (LTC)", "FTX Token (FTT)", "Stellar (XLM)", "Cronos (CRO)", "NEAR Protocol (NEAR)", "Algorand (ALGO)", "Monero (XMR)", "Bitcoin Cash (BCH)", "Flow (FLOW)", "ApeCoin (APE)", "VeChain (VET)", "Filecoin (FIL)", "Chiliz (CHZ)", "Toncoin (TON)", "Internet Computer (ICP)", "Hedera (HBAR)", "Terra Classic (LUNC)", "Quant (QNT)", "Tezos (XTZ)", "The Sandbox (SAND)", "Decentraland (MANA)", "EOS (EOS)", "Theta Network (THETA)", "Elrond (EGLD)", "Aave (AAVE)", "Axie Infinity (AXS)", "TrueUSD (TUSD)", "Bitcoin SV (BSV)", "Pax Dollar (USDP)", "OKB (OKB)", "KuCoin Token (KCS)", "Zcash (ZEC)", "eCash (XEC)", "IOTA (MIOTA)", "BitTorrent - New (BTT)", "The Graph (GRT)", "USDD (USDD)", "Huobi Token (HT)", "Maker (MKR)", "PancakeSwap (CAKE)", "Neutrino USD (USDN)", "Klaytn (KLAY)"];
const currencies = ["New Zealand dollar (NZD)", "Australian dollar (AUD)", "Singapore dollar (SGD)", "Brunei dollar (BND)", "Libyan dinar (LYD)", "Canadian dollar (CAD)", "United States dollar (USD)", "Swiss franc (CHF)", "Euro (EUR)", "Cayman Islands dollar (KYD)", "Gibraltar pound (GIP)", "Pound sterling (GBP)", "Jordan dinar (JOD)", "Omani rial (OMR)", "Bahrain dinar (BHD)", "Kuwaiti dinar (KWD)", "Japanese Yen (JPY)", "South African Rand (ZAR)"];
const daysOfWeek = ["Monday", "Tuesday", "Wednesday", "Thursday", "Friday", "Saturday", "Sunday"];
const dinosaurs = ["Pterodactyl", "Lirainosaurus", "Iguanodon", "Allosaurus", "Brontosaurus", "Gallimimus", "Isanosaurus", "Mosasaurus", "Diplodocus", "Tyrannosaurus Rex", "Red and black Styracosaurus", "Roaring Baryonyx", "Raptorex", "Stegosaurus", "Carnotaurus", "Tsintaosaurus", "Coelophysis", "Triceratops", "Ankylosaurus", "Parasaurolophus", "Europasaurus", "Andesaurus", "Spinosaurus", "Silvisaurus", "Brachiosaurs"];
const dogs = ["English Cocker Spaniel", "Portuguese Water Dog", "St.Bernard", "Akita", "Chesapeake Bay Retriever", "Shiba Inu", "West Highland White Terrier", "Bichon Frise", "Rhodesian Ridgeback", "Belgian Malinoi", "Newfoundland", "Weimaraner", "Collie", "Basset Hound", "Maltese", "Chihuahua", "Vizsla", "Border Collie", "Mastiff", "Pug", "Cane Corso", "Miniature American Shepherd", "Cocker Spaniel", "English Springer Spaniel", "Brittany", "Shetland Sheepdog", "Pomeranian", "Bernese Mountain Dog", "Havanese", "Boston Terrier", "Shih Tzu", "Doberman Pinscher", "Miniature Schnauzer", "Great Dane", "Cavalier King Charles Spaniel", "Siberian Husky", "Boxer", "Australian Shepherd", "Yorkshire Terrier", "Dachshund", "Pembroke Welsh Corgi", "German Shorthaired Pointer", "Rottweiler", "Beagle", "Poodle", "Bulldog", "French Bulldog", "Golden Retriever", "German Shepherd", "Labrador Retriever"];
const extensions = [".mid", ".mp3", ".ogg", ".wav", ".pkg", ".rar", ".rpm", ".zip", ".csv", ".dat", ".db", ".log", ".mdb", ".sav", ".sql", ".tar", ".xml", ".apk", ".bat", ".bin", ".com", ".jar", ".msi", ".py", ".ai", ".bmp", ".gif", ".ico", ".jpg", ".png", ".psd", ".tif", ".aspx", ".css", ".html", ".js", ".php", ".py", ".rss", ".xhtml", ".xls", ".xlsm", ".xlsx", ".bak", ".cab", ".cfg", ".dll", ".ico", ".ini", ".lnk", ".msi", ".sys", ".tmp", ".avi", ".flv", ".mkv", ".mov", ".mp4", ".mpg", ".vob", ".wmv"];
const firstNames = ["James", "Mary", "Robert", "Patricia", "John", "Jennifer", "Michael", "Linda", "David", "Elizabeth", "William", "Barbara", "Richard", "Susan", "Joseph", "Jessica", "Thomas", "Sarah", "Charles", "Karen", "Christopher", "Lisa", "Daniel", "Nancy", "Matthew", "Betty", "Anthony", "Margaret", "Mark", "Sandra", "Donald", "Ashley", "Steven", "Kimberly", "Paul", "Emily", "Andrew", "Donna", "Joshua", "Michelle", "Kenneth", "Carol", "Kevin", "Amanda", "Brian", "Dorothy", "George", "Melissa", "Timothy", "Deborah", "Ronald", "Stephanie", "Edward", "Rebecca", "Jason", "Sharon", "Jeffrey", "Laura", "Ryan", "Cynthia", "Jacob", "Kathleen", "Gary", "Amy", "Nicholas", "Angela", "Eric", "Shirley", "Jonathan", "Anna", "Stephen", "Brenda", "Larry", "Pamela", "Justin", "Emma", "Scott", "Nicole", "Brandon", "Helen", "Benjamin", "Samantha", "Samuel", "Katherine", "Gregory", "Christine", "Alexander", "Debra", "Frank", "Rachel", "Patrick", "Carolyn", "Raymond", "Janet", "Jack", "Catherine", "Dennis", "Maria", "Jerry", "Heather", "Tyler", "Diane", "Aaron", "Ruth", "Jose", "Julie", "Adam", "Olivia", "Nathan", "Joyce", "Henry", "Virginia", "Douglas", "Victoria", "Zachary", "Kelly", "Peter", "Lauren", "Kyle", "Christina", "Ethan", "Joan", "Walter", "Evelyn", "Noah", "Judith", "Jeremy", "Megan", "Christian", "Andrea", "Keith", "Cheryl", "Roger", "Hannah", "Terry", "Jacqueline", "Gerald", "Martha", "Harold", "Gloria", "Sean", "Teresa", "Austin", "Ann", "Carl", "Sara", "Arthur", "Madison", "Lawrence", "Frances", "Dylan", "Kathryn", "Jesse", "Janice", "Jordan", "Jean", "Bryan", "Abigail", "Billy", "Alice", "Joe", "Julia", "Bruce", "Judy", "Gabriel", "Sophia", "Logan", "Grace", "Albert", "Denise", "Willie", "Amber", "Alan", "Doris", "Juan", "Marilyn", "Wayne", "Danielle", "Elijah", "Beverly", "Randy", "Isabella", "Roy", "Theresa", "Vincent", "Diana", "Ralph", "Natalie", "Eugene", "Brittany", "Russell", "Charlotte", "Bobby", "Marie", "Mason", "Kayla", "Philip", "Alexis", "Louis", "Lori"];
const foodCategories = ["Fruit and vegetables", "Starchy food", "Dairy", "Protein", "Fat"];
const fruits = ["Apples", "Blueberries", "Bananas", "Oranges", "Dragon fruit", "Mango", "Avocado"];
const genders = ["male", "female"];
const hobbies = ["Chess", "Board games", "Video games", "Poker", "Card games", "Jigsaw puzzles", "Sudoku", "Crosswords", "Writing", "Blogging", "Podcasting", "Photography", "Travel", "Sports", "Yoga", "Dance", "Art", "Reading", "Making music", "Listening to music"];
const ingredients = ["Olive oil", "All purpose flour", "Butter", "Chicken", "Sugar", "Salt", "Egg", "Rice", "Vegetable oil", "Pork", "Beef", "Cheese", "Garlic", "Orange", "Turkey", "Onion", "Corn", "Whole milk", "Mayonnaise", "Chiles", "Almonds", "Bacon", "Mushrooms", "Coconut", "Beets", "Strawberries", "Fennel", "Lamb", "Apple", "Shrimp"];
const instruments = ["Accordion", "Bagpipe", "Banjo", "Bass drum", "Bass guitar", "Bell", "Bongo drum", "Bugle", "Castanets", "Cello", "Clarinet", "Concertina", "Conga", "Cornet", "Cymbal", "Double bass", "Drums", "Electric guitar", "Flute", "French horn", "Glockenspiel", "Gong", "Grand piano", "Guitar", "Harmonica", "Harp", "Keyboard", "Mandolin", "Maracas", "Marimba", "Microphone", "Oboe", "Organ", "Pan flute", "Piano", "Recorder", "Saxophone", "Sitar", "Snare drum", "Tambourine", "Timpani", "Triangle", "Trombone", "Trumpet", "Tuba", "Ukulele", "Vibraphone", "Violin", "Xylophone", "Zither"];
const itJobTitles = ["Computer systems manager", "Network architect", "Systems analyst", "IT coordinator", "Network administrator", "Network engineer", "Service desk analyst", "System administrator", "Wireless network engineer", "Database administrator", "Database analyst", "Data quality manager", "Database report writer", "SQL database administrator", "Big data engineer / architect", "Business intelligence specialist / analyst", "Business systems analyst", "Data analyst", "Data analytics developer", "Data modeling analyst", "Data scientist", "Data warehouse manager", "Data warehouse programming specialist", "Intelligence specialist", "Back - end developer", "Cloud / software architect", "Cloud / software developer", "Cloud / software applications engineer", "Cloud system administrator", "Cloud system engineer", "DevOps engineer", "Front - end developer", "Full - stack developer", "Java developer", "Platform engineer", "Release manager", "Reliability engineer", "Software engineer", "Software quality assurance analyst", "UI (user interface) designer", "UX (user experience) designer", "Web developer", "Application security administrator", "Artificial intelligence security specialist", "Cloud security specialist", "Cybersecurity hardware engineer", "Cyberintelligence specialist", "Cryptographer", "Data privacy officer", "Digital forensics analyst", "IT security engineer", "Information assurance analyst", "Security systems administrator", "Help desk support specialist", "IT support specialist", "Customer service representative", "Technical product manager", "Product manager", "Project manager", "Program manager", "Portfolio manager"];
const itemConditions = ["New", "Open box", "Certified - Refurbished", "Excellent - Refurbished", "Very Good - Refurbished", "Good - Refurbished", "Seller refurbished", "Used", "For parts or not working"];
const jobCategories = ["Administration, business and management", "Alternative therapies", "Animals, land and environment", "Computing and ICT", "Construction and building", "Design, arts and crafts", "Education and training", "Engineering", "Facilities and property services", "Financial services", "Garage services", "Hairdressing and beauty", "Healthcare", "Heritage, culture and libraries", "Hospitality, catering and tourism", "Languages", "Legal and court services", "Manufacturing and production", "Performing arts and media", "Print and publishing, marketing and advertising", "Retail and customer services", "Science, mathematics and statistics", "Security, uniformed and protective services", "Social sciences and religion", "Social work and caring services", "Sport and leisure", "Transport, distribution and logistics"];
const languages = ["Brazilian Portuguese", "Canadian French", "English", "French Creole", "Haitian Creole", "Navajo", "Quechua", "Spanish", "Catalan", "Danish", "Dutch", "Faroese", "Finnish", "Flemish", "French", "German", "Greek", "Icelandic", "Italian", "Norwegian", "Portuguese", "Spanish", "Swedish", "Belarusian", "Bosnian", "Bulgarian", "Croatian", "Czech", "Estonian", "Hungarian", "Latvian", "Lithuanian", "Macedonian", "Polish", "Romanian", "Russian", "Serbian", "Slovak", "Slovenian", "Turkish", "Ukrainian", "Amharic (Ethiopia)", "Dinka (Sudan)", "Ibo (Nigeria)", "Kirundi", "Mandinka", "Nuer (Nilo - Saharan)", "Oromo (Ethiopia)", "Kinyarwanda", "Shona (Zimbabwe)", "Somali", "Swahili", "Tigrigna (Ethiopia)", "Wolof", "Xhosa", "Yoruba", "Zulu", "Arabic", "Dari", "Farsi", "Hebrew", "Kurdish", "Pashtu", "Punjabi", "Urdu(Pakistan)", "Armenian", "Azerbaijani", "Georgian", "Kazakh", "Mongolian", "Turkmen", "Uzbek"];
const lastNames = ["Smith", "Johnson", "Williams", "Brown", "Jones", "Garcia", "Miller", "Davis", "Rodriguez", "Martinez", "Hernandez", "Lopez", "Gonzalez", "Wilson", "Anderson", "Thomas", "Taylor", "Moore", "Jackson", "Martin", "Lee", "Perez", "Thompson", "White", "Harris", "Sanchez", "Clark", "Ramirez", "Lewis", "Robinson", "Walker", "Young", "Allen", "King", "Wright", "Scott", "Torres", "Nguyen", "Hill", "Flores", "Green", "Adams", "Nelson", "Baker", "Hall", "Rivera", "Campbell", "Mitchell", "Carter", "Roberts"];
const letters = ["A", "B", "C", "D", "E", "F", "G", "H", "I", "J", "K", "L", "M", "N", "O", "P", "Q", "R", "S", "T", "U", "V", "W", "X", "Y", "Z"];
const mobilePhones = ["Samsung Galaxy S22 + (Android) 128 GB", "Samsung Galaxy S22 + (Android) 256 GB", "OnePlus 10 Pro 5G(2022) 256 GB", "Samsung Galaxy S22 Ultra 128 GB", "Samsung Galaxy S22 Ultra 256 GB", "Samsung Galaxy S22 Ultra 512 GB", "OnePlus 10T(2022) 128 GB", "Samsung Galaxy S20 FE 128 GB + 4G", "Samsung Galaxy S21 FE 5G 128 GB", "Samsung Galaxy S21 FE 5G 256 GB", "Samsung Galaxy S22(Android) 128 GB", "Samsung Galaxy S22(Android) 256 GB", "OnePlus Nord(2020) 256 GB", "Samsung Galaxy Z Flip4 128 GB", "OnePlus Nord CE 2(2022) 128 GB", "Motorola Edge 20(2021) 128 GB", "Apple iPhone 12 64 GB", "Apple iPhone 12 128 GB", "Apple iPhone 12 256 GB", "Apple iPhone 12 Mini 5G 128 GB", "Apple iPhone 12 Mini 5G 256 GB", "Apple iPhone 11 64 GB"];
const monthsOfYear = ["January", "February", "March", "April", "May", "June", "July", "August", "September", "October", "November", "December"];
const motorcycles = ["BMW R100S", "Kawasaki AR50", "Ducati 350 Desmo", "Ducati Pantah 500SL", "Harley - Davidson Low Rider", "BMW R69S", "Ducati 1098", "Yamaha XT500", "Norton Commando", "Honda SP1 / SP2", "Honda VRF 800", "Aprilia Tuono", "Yamaha SDR 200", "Triumph Tiger 900", "BMW R1200GS", "KTM 1190", "Yamaha Thundercat", "Honda Pan European", "Indian Scout", "BMW R1200RT", "Ducati Multistrada", "Suzuki V Strom 650", "Harley Davidson Road King", "Honda Blackbird", "Kawasaki W800", "Triumph X75 Hurricane", "MV Agusta 600GT", "Kawasaki Versys", "Yamaha PW50", "Suzuki 600 Bandit", "Kawasaki Ninja H2R", "Kawasaki Eliminator", "KTM RC8", "Suzuki GSXR750", "Ducati 916", "Honda CBR900R ‘Urban Tiger’ Fireblade", "Triumph Triple Speed", "Kawasaki ZX - 10 Tomcat", "Honda Dominator 650", "Suzuki Boulevard", "Keeway Cruiser 250", "Suzuki Intruder", "Ducati 900SS", "Honda CB750", "Indian Chief Vintage", "BMW HP4", "Suzuki Marauder", "Harley Davidson Softail", "Kawasaki Z1", "Yamaha Road Star", "BSA BANTAM", "Yamaha Virago", "Triumph Thunderbird 900", "Kawasaki ZZR600", "Honda C100 Super Cub", "Suzuki TL1000S", "Yamaha RD350LC", "Honda 400 Four", "Moto Guzzi Le Mans", "Yamaha FS1 - E", "BSA Rocket / Triumph Trident", "Velocette Thruxton", "250 Norton Jubilee", "Ariel Square 4 MK2", "Triumph Thruxton", "Norton Commando 961", "Moto Guzzi V7 Racer", "Royal Enfield Continental GT", "Honda 90", "Moto Morini 350 Sport", "Triumph Bonneville", "Panther Model", "Yamaha R1", "Triumph Model H", "Metisse Desert Racer", "Brough Superior SS100", "Velocette Venom", "Manx Norton", "Series C Vincent Black Shadow", "BSA Gold Star"];
const mountains = ["Himalayas", "Karakoram", "Hindu Kush", "Kongur Shan", "Daxue Mountains", "Pamir Mountain", "Kakshaal Too", "Nyenchen Tanglha", "Andes", "Kunlun Mountains", "Cordillera de la Ramada", "Tian Shan", "Hindu Raj", "Cordillera Occidental", "Alaska Range", "Saint Elias Mountains", "Eastern Rift mountains", "Sierra Nevada de Santa Marta", "Caucasus Mountains", "Trans - Mexican Volcanic Belt", "Alborz", "Yun Range", "Bogda Shan", "Cordillera Oriental", "Armenian Highlands", "Rwenzori Mountains", "Wrangell Mountains", "Sierra Nevada de Mérida", "Trans - Ili Alatau", "Sentinel Range", "Sudirman Range", "Alps", "Kamchatka", "Semien Mountains", "Bismarck Range", "Virunga Mountains", "Altai Mountains", "Sierra Nevada", "Sawatch Range (Rocky Mountains)", "Cascade Range", "Sierra Madre de Chiapas", "Atlas Mountains", "Finisterre Range", "Crocker Range, Borneo", "Cameroon line", "Coast Mountains", "Chugach Mountains", "Canadian Rockies", "Yushan Range", "Baluchestan Mountains", "Saur Mountain", "Patkai", "Cordillera de Talamanca", "Barisan Mountains, Sumatra", "Ross Island", "Honshu", "Southern Alps", "Tenerife", "Watkins Range", "Tengger Range", "Owen Stanley Range", "Sarawat Mountains", "Sredinny Range", "Sierra Nevada", "Latimojong", "Tibesti Mountains", "Pyrenees", "Sicily", "Siple Island", "Cordillera Central, Hispaniola", "Réunion", "Al Hajar Mountains", "Cerro de la Neblina", "Douglas Range, Alexander", "Timor", "Apo-Talomo, Mindanao", "Allardyce Range", "Cordillera Central, Luzon", "Madagascar", "Aleutian Range", "Fogo"];
const movieGenres = ["Action", "Adventure", "Comedy", "Crime and mystery", "Fantasy", "Historical", "Horror", "Romance", "Satire", "Science fiction", "Speculative", "Thriller", "Western"];
const movies = ["The Shawshank Redemption (1994)", "The Godfather (1972)", "The Dark Knight (2008)", "The Godfather Part II (1974)", "12 Angry Men (1957)", "Schindler's List (1993)", "The Lord of the Rings: The Return of the King (2003)", "Pulp Fiction (1994)", "The Lord of the Rings: The Fellowship of the Ring (2001)", "The Good, the Bad and the Ugly (1966)", "Forrest Gump (1994)", "Fight Club (1999)", "Inception (2010)", "The Lord of the Rings: The Two Towers (2002)", "Star Wars: Episode V - The Empire Strikes Back (1980)", "The Matrix (1999)", "Goodfellas (1990)", "One Flew Over the Cuckoo's Nest (1975)", "Se7en (1995)", "Seven Samurai (1954)", "It's a Wonderful Life (1946)", "The Silence of the Lambs (1991)", "City of God (2002)", "Saving Private Ryan (1998)", "Life Is Beautiful (1997)", "The Green Mile (1999)", "Interstellar (2014)", "Star Wars: Episode IV - A New Hope (1977)", "Terminator 2: Judgment Day (1991)", "Back to the Future (1985)", "Spirited Away (2001)", "Psycho (1960)", "The Pianist (2002)", "Léon: The Professional (1994)", "Parasite (2019)", "The Lion King (1994)", "Gladiator (2000)", "38. American History X (1998)", "The Departed (2006)", "The Usual Suspects (1995)", "The Prestige (2006)", "Casablanca (1942)", "Whiplash (2014)", "The Intouchables (2011)", "Grave of the Fireflies (1988)", "Harakiri (1962)", "Modern Times (1936)", "Once Upon a Time in the West (1968)", "Rear Window (1954)", "Alien (1979)"];
const musicGenres = ["Pop", "Hip hop", "Rock", "Rhythm and blues", "Soul", "Reggae", "Country", "Funk", "Folk", "Jazz", "Disco", "Classical", "Electronic", "Latino", "Blues", "New Age", "Vocal", "Christian", "Ska", "Traditional"];
const oceans = ["Pacific Ocean", "Atlantic Ocean", "Indian Ocean", "Southern Ocean", "Arctic Ocean"];
const os = ["MS Windows", "Ubuntu", "Mac OS", "Fedora", "Solaris", "Free BSD", "Chrome OS"];
const painters = ["Pablo Picasso", "Giotto di Bondone", "Leonardo da Vinci", "Paul Cezanne", "Rembrandt van Rijn", "Diego Velazquez", "Wassily Kandinsky", "Claude Monet", "Ottavio Leoni", "Jan van Eyck", "William Turner", "Albrecht Durer", "Michelangelo Buonarroti", "Francisco de Goya", "Vincent van Gogh", "Edouard Manet", "Henri Matisse", "Raffaello Sanzio", "Jackson Pollock", "Hilma af Klint", "El Greco", "Paul Gauguin", "Jean - Michel Basquiat", "Edvard Munch", "Titian", "Francis Bacon", "Andy Warhol", "Sir Peter Paul Rubens", "Johannes Vermeer", "Joan Miro", "Masaccio", "Artemisia Gentileschi", "Piero della Francesca", "Piet Mondrian", "Gustave Courbet", "Nicolas Poussin", "Gustav Klimt", "Eugene Delacroix", "Paolo Uccello", "William Blake", "Caspar David Friedrich", "Frida Kahlo", "Kazimir Malevich", "Winslow Homer", "Gerhard Richter", "Marcel Duchamp", "Sandro Botticelli", "Edward Hopper", "Jenny Saville"];
const paintings = ["Composition 8", "Royal Red and Blue", "Starry Night", "Beheading of Saint John the Baptist", "Guernica", "Night Watch", "The Persistence of Memory", "Luncheon on the Boating Party", "No. 5, 1948", "Water Lilies", "Landscape with the Fall of Icarus", "Las Meninas", "Three Musicians", "A Sunday Afternoon on the Island of La Grande Jatte", "Impression, Sunrise", "The Triumph of Galatea", "View of Toledo", "The Tower of Babel", "The Dance", "The Swing", "The Gleaners", "The Flower Carrier", "The Kiss", "Portrait de L’artiste Sans Barbe", "Whistler’s Mother", "Bal du Moulin de la Galette", "The Son of Man", "Cafe Terrace at Night", "American Gothic", "Les Demoiselles d’Avignon", "The Grand Odalisque", "The Liberty leading the people", "Napoleon crossing the Alps", "The Sleeping Gypsy", "Primavera", "Dogs Playing Poker", "Portrait of Dora Maar", "Massacre of the Innocents", "Portrait of Madame Recamier", "Sistine Chapel Ceiling", "The Birth of Venus", "The Arnolfini Marriage", "School of Athens", "Olympia", "The Third of May", "Creation of Adam", "The Scream", "The Last Supper", "Girl with a Pearl Earring", "Mona Lisa"];
const philosophers = ["Thomas Aquinas", "Aristotle", "Confucius", "René Descartes", "Ralph Waldo Emerson", "Michel Foucault", "David Hume", "Immanuel Kant", "Søren Kierkegaard", "Lao - Tzu", "John Locke", "Niccolo Machiavelli", "Karl Marx", "John Stuart Mill", "Friedrich Nietzsche", "Plato", "Jean - Jacques Rousseau", "Jean - Paul Sartre", "Socrates", "Ludwig Wittgenstein"];
const planets = ["Mercury", "Venus", "Earth", "Mars", "Jupiter", "Saturn", "Uranus", "Neptune"];
const programmingLanguages = ["Javascript", "Python", "Go", "Java", "Kotlin", "PHP", "C#", "Swift", "R", "Ruby", "C and C++", "Matlab", "Typescript", "Scala"];
const quotesLatin = ["Pulvis et umbra sumus.", "humani nihil a me alienum puto.", "Fiat Lux.", "Labor omnia vincit.", "De malo, bonum.", "Omne bonum a Deo, omne malum ab homine.", "Nota res mala, optima.", "Ars longa, vita brevis.", "Omnis cum in tenebris praesertim vita laboret.", "Sic vita fluit, dum stare videtur.", "Vivamus, moriendum est.", "Mors ultima ratio.", "Mors certa, hora incerta.", "Non omnis moriar.", "Omnes una manet nox.", "Tantum religio potuit suadere malorum.", "Deus vult.", "Permitte divis cetera.", "Deos fortioribus adesse.", "Cito fit quod dii volunt.", "In primis venerare Deos.", "Vocatus atque non vocatus, Deus aderit.", "Video meliora, proboque, deteriora sequor.", "Rex non potest peccare.", "Abusus non tollit usum.", "Ora et Labora.", "Credo quia absurdum.", "Quod semper, quod ubique, quo ab omnibus.", "Flectere si nequeo superos, Acheronta movebo.", "Vada retro me, Satana.", "Omne ignotum pro magnifico.", "Vi Veri Veniversum Vivus Vici.", "Vitam impendere vero.", "Sic transit gloria mundi.", "Et in Arcadia ego.", "Tempus edax rerum.", "Omnes vulnerant, ultima necat.", "Ex hoc momento pendet aeternitas.", "Fugit inreparabile tempus.", "Serius est quam cogitas.", "Lente hora, celeriter anni.", "In saecula saeculorum.", "Exegi monumentum aere perennius.", "Caelesti sumus omnes semine oriundi.", "Veritas odit moras.", "Lente hora, celeriter anni.", "Si post fata venit gloria, non propero.", "Potius sero quam numquam.", "Bis dat, qui dat celeriter.", "Plaudite, amici, comedia finita est!", "Finis coronat opus.", "Omnes vulnerant, ultima necat.", "Quod nocet, saepe docet.", "Fas est ab hoste doceri.", "Quae nocent, saepe docent.", "Qui dormit, non peccat.", "Natura abhorret a vacua.", "Aut viam inveniam aut faciam.", "Via trita, via tuta.", "Omnium rerum principia parva sunt.", "Novus ordo seclorum.", "Quot homines tot sententiae: suus cuique mos.", "Canis caninam non est.", "Si parva licet componere magnis.", "Summum jus, summa injuria.", "Ubi bene, ibi patria.", "Abusus non tollit usum.", "Memento mori.", "Nil homini certum est.", "Umbra sicut hominis vita.", "Et in Arcadia ego.", "Semper idem.", "Quinon proficit deficit.", "Nihil sub sole novum.", "Exceptio probat regulam de rebus non exceptis."];
const religions = ["Judaism", "Christianity", "Islam", "Hinduism", "Buddhism", "Confucianism", "Taoism"];
const schoolGradesLettered = ["A", "B", "C", "D", "E", "F"];
const schoolGradesNumbered = [1, 2, 3, 4, 5];
const schoolSubjects = ["Reading", "Language arts", "Speech and Debate", "English", "Basic Math", "Pre - algebra", "Consumer Math", "Algebra", "Geometry", "Honors Math in Algebra or Geometry", "Life Science", "Earth Science", "Physical Science", "Health", "Social Studies", "Geography", "Ancient Civilizations", "Medieval and Renaissance", "U.S. History and Government", "French / Spanish / Latin", "Computer Science or Lab", "Art", "Home Economics", "Woodshop", "Metal Shop", "Business Technology", "Instrumental Music", "Band", "Choir", "Drama", "Physical Education", "Sports", "Special Education Day Class", "Resource Program", "Speech Therapy", "Occupational Therapy"];
const scientists = ["Isaac Newton", "Leonhard Euler", "Gottfried von Leibniz", "Carl Friedrich Gauss", "Michael Faraday", "Alhazen Ibn al - Haytham", "Galileo Galilei", "Nikola Tesla", "Marie Sklodowska - Curie", "Albert Einstein", "Euclid of Alexandria", "Louis Pasteur", "Johannes Kepler", "Liu Hui", "Max Planck", "Augustin - Louis Cauchy", "James Clerk Maxwell", "Avicenna of Persia(Ibn Sina)", "Hermann von Helmholtz", "Dmitri Mendeleev", "Robert Koch", "Ernest Rutherford", "Nicolaus Copernicus", "Georg Bernhard Riemann", "Zhang Heng", "Blaise Pascal", "Muhammad Ibn Musa al - Khwarizmi", "Jules Henri Poincaré", "Abu Rayhan al - Biruni", "Isambard Kingdom Brunel"];
const seasons = ["Spring", "Summer", "Autumn", "Winter"];
const sizes = ["XXS", "XS", "S", "M", "L", "XL", "XXL", "3XL", "4XL", "5XL", "6XL", "7XL"];
const skillLevels = ["Novice", "Advanced Beginner", "Competent", "Proficient", "Expert"];
const soccerTeams = ["Man.City", "Bayern Munich", "PSG", "Liverpool", "Barcelona", "Real Madrid", "Ajax", "Tottenham", "Arsenal", "Chelsea", "Dortmund", "RB Salzburg", "Napoli", "AC Milan", "Inter Milan", "Villarreal", "Atlético Madrid", "Benfica", "Porto", "RB Leipzig", "Sporting", "PSV", "Brighton", "Zenit", "Man.United", "Leverkusen", "Athletic Bilbao", "Lyon", "Real Sociedad", "Roma", "Celtic", "Newcastle", "SC Freiburg", "Feyenoord", "Rennes", "Atalanta", "Gladbach", "Union Berlin", "Marseille", "West Ham", "Valencia", "Aston Villa", "1. FC Köln", "Crystal Palace", "Monaco", "Real Betis", "Eintracht", "Lazio", "Hoffenheim", "Club Brugge", "Celta Vigo", "Brentford"];
const socialMedia = ["Facebook", "YouTube", "MySpace", "Twitter", "Flickr", "Photobucket", "LinkedIn", "Digg", "Ning", "Yelp", "Tagged", "Squidoo", "Scribd", "StumbleUpon", "Hi5", "Bebo", "Reddit", "myYearbook", "Technorati", "Kaboodle", "Friendster", "Flixster", "Xanga", "Epinions", "Plaxo", "MyBlogLog", "Yuku", "MetaFilter", "BlackPlanet", "Care2", "GetSatisfaction", "FriendFeed", "ClipMarks", "CafeMom", "NewsVine", "Omgili Ltd", "Gigya", "Ballhype", "Current", "Revver", "Ping", "Tribe", "Magnify", "Diigo", "DZone", "Xing", "Faves", "TwitPic", "Ecademy", "Twine"];
const sportists = ["Sadaharu Oh", "Ronaldo", "Andre Agassi", "Ben Hogan", "Maurice Richard", "Rocky Marciano", "Diego Maradona", "Jerry West", "Cristiano Ronaldo", "LeBron James", "Rickey Henderson", "Kobe Bryant", "Mario Lemieux", "Pete Sampras", "John Elway", "Albert Pujols", "Reggie White", "Bobby Orr", "Mike Tyson", "Brett Favre", "Bo Jackson", "Kareem Abdul - Jabbar", "Barry Sanders", "Michael Phelps", "Joe Montana", "Walter Payton", "Pete Rose", "Deion Sanders", "Roger Federer", "Sugar Ray Robinson", "Peyton Manning", "Ty Cobb", "Barry Bonds", "Nolan Ryan", "Lawrence Taylor", "Ted Williams", "Jerry Rice", "Jackie Robinson", "Willie Mays", "Tiger Woods", "Lance Armstrong", "Jim Brown", "Wilt Chamberlain", "Jim Thorpe", "Pele", "Muhammad Ali", "Babe Ruth", "Wayne Gretzky", "Hank Aaron", "Michael Jordan"];
const sports = ["Soccer", "Golf", "Basketball", "Tennis", "Cricket", "Boxing", "Hockey", "Baseball", "Wrestling", "Chess", "Swimming", "Volleyball", "Rugby", "Athletics", "Bowling", "Skating", "Gymnastics", "Ice Hockey", "Tennis", "Polo"];
const todos = ["Shopping", "Practice", "Pick up children", "Cook dinner", "Prepare guesthouse", "Appointment", "Dentist appointment", "Finish project", "Start project", "Write down ideas about new project", "Deploy application", "Notify all users about the application change", "Prepare for the trip", "Wash hair", "Wash car", "Brush teeth", "Clean the house", "Prepare for the big event", "Prepare for the hike", "Visit family", "School reunion", "Family reunion", "Buy sweets for children", "Buy bread", "Buy grocery", "Practice grammar", "Work out", "Sign up for the new course", "Wash dishes", "Practice Latin vocabulary", "Read that new book", "Buy book about fungi", "Practice algebra", "Practice math", "Learn German irregular verbs", "Get info about astronomy", "Buy course about programming", "Go on the bike ride", "Find lost keys", "Fix car", "Fix bike", "Fix bicycle", "Buy shoes", "Paint walls", "Practice yoga", "Get children from the park", "Buy new tools", "Fix broken tools", "Call barbara", "Call Steve", "Call Jessica", "Call aunt Agatha", "Make appointment"];
const tools = ["Hammer", "Screwdriver", "Mallet", "Axe", "Saw", "Wrench", "Monkeywrench", "Chisel", "Pliers", "Hacksaw", "Phillips screwdriver", "Hatchet", "Plane", "Scraper", "Bradawl", "Coping saw"];
const vegetables = ["Carrots", "Potato", "Tomato", "Onions", "Broccoli", "Mushroom", "Lettuce", "Capsicum"];
const vehicles = ["Van", "Taxi", "Bus", "Ambulance", "Skateboard", "Bicycle", "Mountain bike", "Scooter", "Motorcycle", "Fire engine", "Crane", "Forklift", "Tractor", "Recycling truck", "Cement mixer", "Dump truck", "Subway", "Aerial tramway", "Helicopter", "Airplane", "Balloon", "Tram", "Carriage", "Rowboat", "Boat", "Train"];
const words = ["high", "every", "near", "add", "food", "between", "own", "below", "country", "plant", "last", "school", "father", "keep", "tree", "never", "start", "city", "earth", "eye", "light", "thought", "head", "under", "story", "Words", "saw", "left", "few", "while", "along", "might", "close", "something", "seem", "next", "hard", "open", "example", "begin", "life", "always", "those", "both", "paper", "together", "got", "group", "often", "run", "Words", "important", "until", "children", "side", "feet", "car", "mile", "night", "walk", "white", "sea", "began", "grow", "took", "river", "four", "carry", "state", "once", "book", "hear", "stop", "without", "second", "later", "Words", "miss", "idea", "enough", "eat", "face", "watch", "far", "Indian", "really", "almost", "let", "above", "girl", "sometimes", "mountain", "cut", "young", "talk", "soon", "list", "song", "being", "leave", "family", "over", "new", "sound", "take", "only", "little", "work", "know", "place", "year", "live", "me", "back", "give", "most", "very", "after", "thing", "our", "just", "name", "good", "sentence", "man", "think", "Words", "say", "great", "where", "help", "through", "much", "before", "line", "right", "too", "mean", "old", "any", "same", "tell", "boy", "follow", "came", "want", "show", "also", "around", "form", "three", "small", "Words", "set", "put", "end", "does", "another", "well", "large", "must", "big", "even", "such", "because", "turn", "here", "why", "ask", "went", "men", "read", "need", "land", "different", "home", "us", "move", "Words", "try", "kind", "hand", "picture", "again", "change", "off", "play", "spell", "air", "away", "animal", "house", "point", "page", "letter", "mother", "answer", "found", "study", "still", "learn", "should", "America", "world"];
const writers = ["Gabriel Garcia Marquez", "Robert Harris", "Ralph Ellison", "Giles Coren", "Julie Burchill", "Joseph Freiherr von Eichendorff", "Martin Amis", "E.B.White", "John Milton", "Giuseppe Tomasi di Lampedusa", "Michael Azerrad", "J.K.Rowling", "Richard Littlejohn", "Thomas Mann", "David Berman", "Bret Easton Ellis", "Gary Snyder", "Philip K.Dick", "Peter Cook", "Jorge Luis Borges", "Pablo Neruda", "Suetonius", "Arthur Rimbaud", "Gore Vidal", "Jane Austen", "Francis Bacon", "James Thurber", "Iris Murdoch", "Evelyn Waugh", "Saul Bellow", "Marcel Proust", "Wole Soyinka", "J.R.R.Tolkien", "Don DeLillo", "Richard Yates", "John Updike", "Virginia Woolf", "Joseph Conrad", "Cormac McCarthy", "Primo Levi", "James Baldwin", "William Shakespeare", "Woody Allen", "Leo Tolstoy", "George Eliot", "Homer", "J.D.Salinger", "F.Scott Fitzgerald", "Charles Dickens", "Ivan Turgenev", "John Donne"];
const zodiacSigns = ["Aries", "Taurus", "Gemini", "Cancer", "Leo", "Virgo", "Libra", "Scorpio", "Saggitarius", "Capricorn", "Aquarius", "Pisces"];

module.exports = {
  actors,
  animals,
  artists,
  bands,
  books,
  browsers,
  cars,
  cats,
  chemicalElements,
  chessPlayers,
  cities,
  colors,
  continents,
  countries,
  cryptoCurrencies,
  currencies,
  daysOfWeek,
  dinosaurs,
  dogs,
  extensions,
  firstNames,
  foodCategories,
  fruits,
  genders,
  hobbies,
  ingredients,
  instruments,
  itJobTitles,
  itemConditions,
  jobCategories,
  languages,
  lastNames,
  letters,
  mobilePhones,
  monthsOfYear,
  motorcycles,
  mountains,
  movieGenres,
  movies,
  musicGenres,
  oceans,
  os,
  painters,
  paintings,
  philosophers,
  planets,
  programmingLanguages,
  quotesLatin,
  religions,
  schoolGradesLettered,
  schoolGradesNumbered,
  schoolSubjects,
  scientists,
  seasons,
  sizes,
  skillLevels,
  soccerTeams,
  socialMedia,
  sportists,
  sports,
  todos,
  tools,
  vegetables,
  vehicles,
  words,
  writers,
  zodiacSigns
}
